In [ ]:
# Cheney Zhang Homework #3 Question #1

import numpy as np

# Given input matrix
input_matrix = np.array([[0, 0, 0, 0, 0],
                         [0, 1, 2, 3, 0],
                         [0, 4, 5, 6, 0],
                         [0, 7, 8, 9, 0],
                         [0, 0, 0, 0, 0]])

# Given Kernel matrix
kernel = np.array([[0, 1],
                   [2, 3]])

# Part a: 2D convolution operation (without padding)
output_size = 4
output_matrix_without_padding = np.zeros((output_size, output_size))

for i in range(output_size):
    for j in range(output_size):
        output_matrix_without_padding[i, j] = np.sum(input_matrix[i:i+2, j:j+2] * kernel)

# Part b: 2D convolution operation (with padding)
input_matrix_with_padding = np.pad(input_matrix, 1)
output_size_with_padding = 6
output_matrix_with_padding = np.zeros((output_size_with_padding, output_size_with_padding))

for i in range(output_size_with_padding):
    for j in range(output_size_with_padding):
        output_matrix_with_padding[i, j] = np.sum(input_matrix_with_padding[i:i+2, j:j+2] * kernel)

print("Part a: ",output_matrix_without_padding)
print("Part b: ", output_matrix_with_padding)

Part a:  [[ 3.  8. 13.  6.]
 [13. 25. 31. 12.]
 [25. 43. 49. 18.]
 [ 7.  8.  9.  0.]]
Part b:  [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  3.  8. 13.  6.  0.]
 [ 0. 13. 25. 31. 12.  0.]
 [ 0. 25. 43. 49. 18.  0.]
 [ 0.  7.  8.  9.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
